using System;
using System.Threading;
using Apache.NMS;

namespace MinimalDarwinPushPortClientV16
{
    /*
     * This sample illustrates how to use .Net generally and C# specifically to 
     * receive and process messages from the Darwin Push Port.  Originally written by Chris Bailiss.
     * The message schemas are included in the project for information only.
     * The classes in the rttiPPT.cs file were autogenerated from these schemas.
     * This sample makes use of the Apache NMS Messaging API - http://activemq.apache.org/nms/
     * This sample was built against v1.7.0 of the API.  
     * The Apache.NMS and Apache.NMS.ActiveMQ assemblies can be downloaded from http://activemq.apache.org/nms/download.html
     */

    internal static class Program
    {
        private static int _miMessageCount;

        private static void Main()
        {
            try
            {
                // CONNECTION SETTINGS:  In your code, move these into some form of configuration file / table
                // *** change the lines below to match your personal details *** 
                const string sConnectUrl = "activemq:tcp://HOSTNAME:61616?connection.watchTopicAdvisories=false";
                const string sUser = "TOPIC-USERNAME";
                const string sPassword = "TOPIC-PASSWORD";
                const string sTopic = "darwin.pushport-v16";

                if (sUser == "TOPIC-USERNAME" || sPassword == "TOPIC-PASSWORD" || sConnectUrl.Contains("HOSTNAME"))
                {
                    Console.WriteLine("DARWIN PUSH PORT RECEIVER SAMPLE: ");
                    Console.WriteLine();
                    Console.WriteLine("ERROR:  Please update the source code (in the Program.cs file) to use your user name and password!");
                    Console.ReadLine();
                    return;
                }

                Console.WriteLine("Darwin v16 Minimal Example");
                Console.WriteLine("Starting...");

                IConnectionFactory oConnectionFactory = new NMSConnectionFactory(new Uri(sConnectUrl));
                var oConnection = oConnectionFactory.CreateConnection(sUser, sPassword);
                oConnection.ClientId = sUser;
                oConnection.ExceptionListener += OnConnectionException;
                var oSession = oConnection.CreateSession();
                var oTopic = oSession.GetTopic(sTopic);
                var oConsumer = oSession.CreateConsumer(oTopic);

                oConsumer.Listener += OnMessageReceived;

                oConnection.Start();

                var dtRunUntil = DateTime.Now.AddSeconds(30);
                while (DateTime.Now < dtRunUntil)
                {
                    Thread.Sleep(50);
                }

                oConnection.Stop();

                var dtWaitUntil = DateTime.Now.AddSeconds(2);
                while (DateTime.Now < dtWaitUntil)
                {
                    Thread.Sleep(50);
                }

                Console.WriteLine("Press any key to finish");
                Console.ReadKey();

            }
            catch (Exception oException)
            {
                Console.WriteLine("FATAL ERROR:  " + oException.GetType().FullName);
                Console.WriteLine(oException.Message);
            }
        }

        private static void OnConnectionException(Exception oException)
        {
            Console.WriteLine("CONNECTION ERROR:  " + oException.GetType().FullName);
            Console.WriteLine(oException.Message);
        }

        private static void OnMessageReceived(IMessage message)
        {
            try
            {
                OpenRailBytesMessage oMessage = null;
                if (message is IBytesMessage msgBytes) oMessage = new OpenRailBytesMessage(msgBytes.Content);

                if (oMessage == null) return;
                _miMessageCount++;
                if (_miMessageCount % 25 != 0) return;
                var oPPort = DarwinMessageHelper.GetMessageAsObjects(oMessage.Bytes);
                var sMessageType = DarwinMessageHelper.GetMessageDescription(oPPort);
                var iSequenceNumber = Convert.ToInt64(message.Properties["SequenceNumber"]);
                var iPushPortSequence = Convert.ToInt64(message.Properties["PushPortSequence"]);
                Console.WriteLine($"{DateTime.Now:HH:mm:ss.fff}: Total Messages Received = {_miMessageCount}: Last Message = {sMessageType}, SeqNum = {iSequenceNumber}, PPSeqNum = {iPushPortSequence}");
            }
            catch (Exception oException)
            {
                Console.WriteLine("MESSAGE ERROR:  " + oException.GetType().FullName);
                Console.WriteLine(oException.Message);
            }
        }
    }
}
